inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - config/deploy.rb
    - bin/bundle
    - config/initializers/version.rb
