inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - config/deploy.rb
    - bin/bundle
    - config/initializers/version.rb
    - db/schema.rb
