inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 14

Metrics/ClassLength:
  Max: 200

Rails/BulkChangeTable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - db/migrate/20230331091323_add_category_and_user_to_category_interest.rb # FK doesn't need default

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - config/deploy.rb
    - bin/bundle
    - config/initializers/version.rb
    - db/schema.rb
    - db/seeds.rb
